let nom = null;
let age = 0;
let ville = "";
let score = undefined;
let actif = false;
console.log('nom ?? "valeur par défaut"    -> ' + (nom ?? "valeur par défaut"));
console.log('age ?? "valeur par défaut"    -> ' + (age ?? "valeur par défaut"));
console.log('ville ?? "valeur par défaut"  -> ' + (ville ?? "valeur par défaut"));
console.log('score ?? "valeur par défaut"  -> ' + (score ?? "valeur par défaut"));
console.log('actif ?? "valeur par défaut"  -> ' + (actif ?? "valeur par défaut"));
console.log('---');
console.log('nom || "valeur par défaut"    -> ' + (nom || "valeur par défaut"));
console.log('age || "valeur par défaut"    -> ' + (age || "valeur par défaut"));
console.log('ville || "valeur par défaut"  -> ' + (ville || "valeur par défaut"));
console.log('score || "valeur par défaut"  -> ' + (score || "valeur par défaut"));
console.log('actif || "valeur par défaut"  -> ' + (actif || "valeur par défaut"));
console.log('---');
let nomCompare = (nom ?? "valeur par défaut") === (nom || "valeur par défaut");
let ageCompare = (age ?? "valeur par défaut") === (age || "valeur par défaut");
let villeCompare = (ville ?? "valeur par défaut") === (ville || "valeur par défaut");
let scoreCompare = (score ?? "valeur par défaut") === (score || "valeur par défaut");
let actifCompare = (actif ?? "valeur par défaut") === (actif || "valeur par défaut");
console.log('nom   : ?? et || -> ' + (nomCompare ? "même résultat" : "résultat différent"));
console.log('age   : ?? et || -> ' + (ageCompare ? "même résultat" : "résultat différent"));
console.log('ville : ?? et || -> ' + (villeCompare ? "même résultat" : "résultat différent"));
console.log('score : ?? et || -> ' + (scoreCompare ? "même résultat" : "résultat différent"));
console.log('actif : ?? et || -> ' + (actifCompare ? "même résultat" : "résultat différent"));